apiVersion: v1
kind: Service
metadata:
  name: giftapp-service
spec:
  type: NodePort
  selector:
    app: giftapp
  ports:
    - protocol: TCP
      port: 3060
      targetPort: 3060
      nodePort: 30036
